import type { SemanticEntity, SemanticKey } from '../model/types';

/**
 * Cozy Pixel World theme contract (ADR-035). A pack maps semantic keys and
 * décor kinds to authored pixel assets under `/world/` (generated by
 * `scripts/gen-world-assets.mjs` — original art only).
 *
 * Animated sprites pack frames horizontally; the renderer animates with
 * `steps()` over `frames`. Procedural `css` assets remain a transitional
 * fallback for keys without authored art.
 */
export type ThemeAsset =
  { kind: 'css'; className: string; label: string } | { kind: 'sprite'; src: string; label: string; frames?: number };

/** Terrain/décor/ambient ids resolved against pack.decor. */
export type DecorKind = string;

export interface WorldThemePack {
  id: string;
  label: string;
  /**
   * Source tile grid (16px assets) × display scale. The renderer quantizes
   * the camera to whole source pixels and integer zoom — never fractional.
   */
  tileSize: number;
  /** Source px per tile (asset grid). */
  sourceTile: number;
  assets: Readonly<Partial<Record<SemanticKey, ThemeAsset>>>;
  /** Façade sprites: project house variants + landmark silhouettes. */
  facades?: Readonly<Partial<Record<string, ThemeAsset>>>;
  /** Terrain tiles, décor sprites, ambient critters. */
  decor?: Readonly<Partial<Record<DecorKind, ThemeAsset>>>;
  /** Interior floor/wall/furniture tiles. */
  interior?: Readonly<Partial<Record<DecorKind, ThemeAsset>>>;
}

export function resolveThemeAsset(pack: WorldThemePack, key: SemanticKey): ThemeAsset {
  return (
    pack.assets[key] ?? {
      kind: 'css',
      className: 'worldTileFallback',
      label: key,
    }
  );
}

/** Prefer façade sprite when the entity carries a theme façade id. */
export function resolveEntityAsset(
  pack: WorldThemePack,
  entity: Pick<SemanticEntity, 'themeKey' | 'facade'>,
): ThemeAsset {
  if (entity.facade) {
    const facadeAsset = pack.facades?.[entity.facade];
    if (facadeAsset) return facadeAsset;
  }
  return resolveThemeAsset(pack, entity.themeKey);
}

export function resolveDecor(pack: WorldThemePack, kind: DecorKind): ThemeAsset | undefined {
  return pack.decor?.[kind];
}

export function resolveInterior(pack: WorldThemePack, kind: DecorKind): ThemeAsset | undefined {
  return pack.interior?.[kind];
}
