"""
workspace — AI workspace scaffolding and session context.

Usage:
    agent-toolkit workspace <subcommand> [args]

Subcommands:
    init [--dir PATH] [--name NAME]   Scaffold a new harness workspace
    context [--workspace PATH]        Output a session state snapshot
    sync [--workspace PATH]           Sync loop escalations into todos

Options:
    --help    Show this help message
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import sys as _sys
if _sys.platform == 'win32':
    try:
        _sys.stdout.reconfigure(encoding='utf-8', errors='replace')
        _sys.stderr.reconfigure(encoding='utf-8', errors='replace')
    except Exception:
        pass


# ---------------------------------------------------------------------------
# Color helpers
# ---------------------------------------------------------------------------

_USE_COLOR = sys.stdout.isatty() and not os.environ.get("NO_COLOR")


def _c(code: str, text: str) -> str:
    return f"\033[{code}m{text}\033[0m" if _USE_COLOR else text


def _blue(t: str) -> str:   return _c("1;34", t)
def _green(t: str) -> str:  return _c("1;32", t)
def _yellow(t: str) -> str: return _c("1;33", t)
def _cyan(t: str) -> str:   return _c("0;36", t)
def _dim(t: str) -> str:    return _c("0;37", t)


# ---------------------------------------------------------------------------
# Workspace root detection
# ---------------------------------------------------------------------------

def _find_workspace(override: str | None = None) -> Path | None:
    """Locate workspace root via env, override, or walking up from CWD."""
    from agent_toolkit._paths import find_workspace_root

    return find_workspace_root(override=override)


# ---------------------------------------------------------------------------
# File helpers
# ---------------------------------------------------------------------------

def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------

_AGENTS_MD_TEMPLATE = """\
# AGENTS.md — AI Workspace Orchestrator

> Generated by: agent-toolkit workspace init
> Customize this file to reflect your team's workflows and tools.

**Purpose**: Session that orchestrates multi-repository work.

## Work Context

- **Repos**: ./projects/ symlinks · ./repos/ cloned on-demand
- **Knowledge**: ./knowledge/ — persistent memory across sessions
- **Personas**: ./personas/ — focused work modes
- **Packs**: ./packs/ — context bundles per client/project

## Available Commands

```
agent-toolkit workspace context        # Print session snapshot
agent-toolkit workspace sync           # Sync loop escalations into todos
agent-toolkit memory add --type <t>    # Add learning/process/todo
agent-toolkit memory search <query>    # Search knowledge base
agent-toolkit memory inject            # Output context block for session
agent-toolkit memory todo              # List pending todos
agent-toolkit project clone <org/repo> # Clone a repo and symlink it
agent-toolkit project list             # List indexed projects
agent-toolkit project scan             # Check project/repo consistency
```

## Operating Rules

- Run `agent-toolkit workspace context` at session start
- Run `agent-toolkit memory search <topic>` before asking known questions
- Save discoveries: `agent-toolkit memory add --type learning "..."`
- Queue background work: `agent-toolkit devcompanion queue <project>`
"""

_KNOWLEDGE_README = """\
# Knowledge Base

Persistent memory across sessions. Add entries with:

```
agent-toolkit memory add --type learning "Always run tests before committing"
agent-toolkit memory add --type process "How to deploy: ..."
agent-toolkit memory add --type todo "Investigate slow query in reports"
```

## Structure

- `learnings/general.md` — factual session learnings
- `processes/<topic>.md` — how-to procedures
- `todos/pending.md` — pending follow-ups
"""

_LEARNINGS_GENERAL = """\
# General Learnings

<!-- Add new entries with: agent-toolkit memory add --type learning "..." -->

| Date | Learning | Context |
|------|----------|---------|
"""

_TODOS_PENDING = """\
# Pending Todos

<!-- Add pending items with date added -->
<!-- agent-toolkit memory add --type todo "description" -->
"""

_PACKS_README = """\
# Packs

Context bundles for switching between clients or projects.

Create a YAML file here:

```yaml
# packs/my-client.yaml
name: my-client
description: Context for my-client engagement
projects:
  - my-client-api
  - my-client-frontend
notes: |
  Key contacts: ...
```

Load with: `agent-toolkit workspace context --pack packs/my-client.yaml`
"""

_PERSONA_IMPLEMENTER = """\
---
allow:
  - write_files
  - run_tests
  - run_build
  - create_commits
deny:
  - merge_prs
  - deploy_production
output_format: code_first
handoffs:
  - when: "implementation complete, needs review"
    to: reviewer
---

# Implementer Persona

> Bias toward action. Write code, run tests, create commits.

## Focus

- Write clean, idiomatic code following project conventions
- Run tests to verify changes work
- Create commits with clear messages
- Ask only when genuinely blocked

## Constraints

- **Do not** merge PRs or deploy to production
- Handoff to **reviewer** when implementation is complete
"""

_PERSONA_REVIEWER = """\
---
allow:
  - read_files
  - run_tests
  - post_comments
  - approve_prs
deny:
  - write_files
  - create_commits
output_format: critique_and_feedback
handoffs:
  - when: "review complete, changes needed"
    to: implementer
  - when: "security concerns found"
    to: architect
---

# Reviewer Persona

> Analyze and critique. No changes — feedback only.

## Focus

- Read code carefully for correctness, clarity, and security
- Run tests to verify coverage
- Post clear, actionable feedback
- Approve PRs when quality bar is met

## Constraints

- **Do not** write or modify files
- **Do not** create commits
- Handoff to **implementer** when changes are needed
"""

_PERSONA_RESEARCHER = """\
---
allow:
  - read_files
  - search_web
  - read_docs
deny:
  - write_files
  - create_commits
  - run_tests
output_format: summary_and_findings
handoffs:
  - when: "research complete, ready to implement"
    to: implementer
  - when: "architectural decision needed"
    to: architect
---

# Researcher Persona

> Explore and summarize. No implementation.

## Focus

- Read codebases to understand structure and patterns
- Search documentation and references
- Produce clear summaries of findings
- Identify options with tradeoffs

## Constraints

- **Do not** modify any files
- **Do not** run tests or builds
- Handoff to **implementer** or **architect** when done
"""

_PERSONA_ARCHITECT = """\
---
allow:
  - read_files
  - write_docs
  - create_adrs
  - design_schemas
deny:
  - write_application_code
  - create_commits
output_format: design_document
handoffs:
  - when: "design finalized, ready to build"
    to: implementer
  - when: "security review needed"
    to: reviewer
---

# Architect Persona

> System design, tradeoffs, ADRs.

## Focus

- Analyze system design and architectural tradeoffs
- Write ADRs (Architecture Decision Records)
- Design schemas, APIs, and data models
- Evaluate technical options at the system level

## Constraints

- **Do not** write application code
- Write design documents and ADRs, not implementation
- Handoff to **implementer** when design is finalized
"""

_GITIGNORE = """\
# Cloned repos (managed by agent-toolkit project clone)
repos/
# Project symlinks (managed by agent-toolkit project clone/add)
projects/
# Active state files
.active-persona
.active-pack
.active-profile
.persona-history
"""


# ---------------------------------------------------------------------------
# Subcommands
# ---------------------------------------------------------------------------

def cmd_init(args: list[str]) -> int:
    """Scaffold a new harness workspace."""
    target_dir = Path.cwd()
    name = ""
    i = 0
    while i < len(args):
        match args[i]:
            case "--dir" if i + 1 < len(args):
                target_dir = Path(args[i + 1]).expanduser().resolve()
                i += 2
            case "--name" if i + 1 < len(args):
                name = args[i + 1]
                i += 2
            case "--help" | "-h":
                print("Usage: agent-toolkit workspace init [--dir PATH] [--name NAME]")
                return 0
            case _:
                print(f"Unknown option: {args[i]}", file=sys.stderr)
                return 1

    if name:
        target_dir = target_dir / name

    target_dir.mkdir(parents=True, exist_ok=True)
    created: list[str] = []

    def _create(rel: str, content: str) -> None:
        path = target_dir / rel
        if not path.exists():
            _write(path, content)
            created.append(rel)
        else:
            print(f"  {_yellow('skip')}  {rel} (already exists)")

    # Core files
    _create("AGENTS.md", _AGENTS_MD_TEMPLATE)
    _create(".gitignore", _GITIGNORE)

    # Knowledge
    _create("knowledge/README.md", _KNOWLEDGE_README)
    _create("knowledge/learnings/general.md", _LEARNINGS_GENERAL)
    _create("knowledge/todos/pending.md", _TODOS_PENDING)

    # Packs
    _create("packs/README.md", _PACKS_README)

    # Personas
    _create("personas/implementer.md", _PERSONA_IMPLEMENTER)
    _create("personas/reviewer.md", _PERSONA_REVIEWER)
    _create("personas/researcher.md", _PERSONA_RESEARCHER)
    _create("personas/architect.md", _PERSONA_ARCHITECT)

    # Directories (gitignored, so just ensure they exist)
    for d in ("projects", "repos"):
        (target_dir / d).mkdir(exist_ok=True)
        gitkeep = target_dir / d / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.touch()
            created.append(f"{d}/.gitkeep")

    print(f"\n{_green('Workspace initialized:')} {target_dir}\n")
    for rel in created:
        print(f"  {_green('++')}  {rel}")
    print()
    print(f"Next steps:")
    print(f"  cd {target_dir}")
    print(f"  agent-toolkit workspace context")
    print(f"  agent-toolkit project clone owner/my-repo")
    print()
    return 0


def cmd_context(args: list[str]) -> int:
    """Output a session state snapshot."""
    workspace_path: str | None = None
    i = 0
    while i < len(args):
        match args[i]:
            case "--workspace" if i + 1 < len(args):
                workspace_path = args[i + 1]
                i += 2
            case "--help" | "-h":
                print("Usage: agent-toolkit workspace context [--workspace PATH]")
                return 0
            case _:
                print(f"Unknown option: {args[i]}", file=sys.stderr)
                return 1

    ws = _find_workspace(workspace_path)
    if ws is None:
        print("Error: workspace not found.", file=sys.stderr)
        print("Set AGENT_TOOLKIT_WORKSPACE or run from inside a workspace directory.", file=sys.stderr)
        return 1

    now = datetime.now(timezone.utc)
    knowledge = ws / "knowledge"
    projects_dir = ws / "projects"
    loops_dir = ws / "loops"
    packs_dir = ws / "packs"

    print()
    print(_blue("=== AI Workspace — Session Context ==="))
    print()
    print(f"Date      : {now.strftime('%Y-%m-%d %H:%M UTC')}")
    print(f"Workspace : {ws}")
    print()

    # Git branch
    try:
        result = subprocess.run(
            ["git", "-C", str(ws), "rev-parse", "--abbrev-ref", "HEAD"],
            capture_output=True, text=True, timeout=5,
        )
        if result.returncode == 0:
            print(f"Branch    : {result.stdout.strip()}")
            print()
    except Exception:
        pass

    # Projects
    print(_blue("── Projects ──────────────────────────────────────────────"))
    project_count = 0
    if projects_dir.is_dir():
        for link in sorted(projects_dir.iterdir()):
            if link.is_symlink():
                target = link.resolve()
                status = _green("ok") if target.exists() else _yellow("broken")
                print(f"  [{status}]  {link.name:30s} -> {link.readlink()}")
                project_count += 1
        if project_count == 0:
            print(_dim("  (no projects indexed — run: agent-toolkit project clone owner/repo)"))
    else:
        print(_dim("  (projects/ directory not found)"))
    print()

    # Pending todos
    print(_blue("── Pending Todos ──────────────────────────────────────────"))
    todos_path = knowledge / "todos" / "pending.md"
    if todos_path.exists():
        content = todos_path.read_text(encoding="utf-8")
        unchecked = [l for l in content.splitlines() if l.startswith("- [ ]")]
        if unchecked:
            for item in unchecked[:10]:
                print(f"  {item}")
            if len(unchecked) > 10:
                print(_dim(f"  ... and {len(unchecked) - 10} more"))
        else:
            print(_dim("  (no pending todos)"))
    else:
        print(_dim("  (no todos file)"))
    print()

    # Recent learnings
    print(_blue("── Recent Learnings ───────────────────────────────────────"))
    learnings_path = knowledge / "learnings" / "general.md"
    if learnings_path.exists():
        content = learnings_path.read_text(encoding="utf-8")
        rows = [l for l in content.splitlines() if re.match(r"^\| \d{4}", l)]
        if rows:
            for row in rows[:3]:
                print(f"  {row}")
        else:
            print(_dim("  (no learnings recorded yet)"))
    else:
        print(_dim("  (no learnings file)"))
    print()

    # Loop status summary
    if loops_dir.is_dir():
        print(_blue("── Loop Status ────────────────────────────────────────────"))
        loop_names = sorted(d.name for d in loops_dir.iterdir() if d.is_dir())
        if loop_names:
            for loop_name in loop_names:
                state_file = loops_dir / loop_name / "STATE.md"
                last_run = "(no STATE.md)"
                if state_file.exists():
                    content = state_file.read_text(encoding="utf-8")
                    # Look for last run date in STATE.md
                    for line in content.splitlines():
                        m = re.search(r"(\d{4}-\d{2}-\d{2})", line)
                        if m:
                            last_run = m.group(1)
                            break
                print(f"  {loop_name:35s} last: {last_run}")
        else:
            print(_dim("  (no loops configured)"))
        print()

    # Active pack
    active_pack_file = ws / ".active-pack"
    if active_pack_file.exists():
        pack = active_pack_file.read_text(encoding="utf-8").strip()
        print(_blue("── Active Pack ────────────────────────────────────────────"))
        print(f"  {pack}")
        print()

    # Active persona
    active_persona_file = ws / ".active-persona"
    if active_persona_file.exists():
        persona = active_persona_file.read_text(encoding="utf-8").strip()
        print(_blue("── Active Persona ─────────────────────────────────────────"))
        print(f"  {persona}")
        print()

    # AGENTS.md hash
    agents_md = ws / "AGENTS.md"
    if agents_md.exists():
        import hashlib
        spec_hash = hashlib.sha256(agents_md.read_bytes()).hexdigest()[:12]
        print(f"Spec      : AGENTS.md@{spec_hash}")
        print()

    print(_blue("──────────────────────────────────────────────────────────"))
    print()
    return 0


def cmd_sync(args: list[str]) -> int:
    """Sync loop escalations into knowledge/todos/pending.md."""
    workspace_path: str | None = None
    i = 0
    while i < len(args):
        match args[i]:
            case "--workspace" if i + 1 < len(args):
                workspace_path = args[i + 1]
                i += 2
            case "--help" | "-h":
                print("Usage: agent-toolkit workspace sync [--workspace PATH]")
                return 0
            case _:
                print(f"Unknown option: {args[i]}", file=sys.stderr)
                return 1

    ws = _find_workspace(workspace_path)
    if ws is None:
        print("Error: workspace not found.", file=sys.stderr)
        print("Set AGENT_TOOLKIT_WORKSPACE or run from inside a workspace directory.", file=sys.stderr)
        return 1

    loops_dir = ws / "loops"
    todos_path = ws / "knowledge" / "todos" / "pending.md"

    if not loops_dir.is_dir():
        print(_dim("No loops/ directory found — nothing to sync."))
        return 0

    today = datetime.now().date().isoformat()
    todos_content = _read(todos_path)
    new_todos: list[str] = []

    for loop_dir in sorted(loops_dir.iterdir()):
        if not loop_dir.is_dir():
            continue
        # Scan for escalation markers in reports and STATE.md
        for candidate in ["report.md", "STATE.md", "request.md"]:
            report = loop_dir / candidate
            if not report.exists():
                continue
            content = report.read_text(encoding="utf-8")
            for line in content.splitlines():
                if any(marker in line.lower() for marker in ["escalat", "action required", "todo:", "follow-up:"]):
                    # Extract the meaningful part
                    clean = line.strip().lstrip("#").lstrip("-").lstrip(">").strip()
                    if len(clean) < 10:
                        continue
                    todo_line = f"- [ ] {today} - [loop:{loop_dir.name}] {clean}"
                    # Avoid duplicates
                    if todo_line not in todos_content and todo_line not in new_todos:
                        new_todos.append(todo_line)

    if not new_todos:
        print(_dim("No escalations found in loop reports."))
        return 0

    # Append new todos
    todos_path.parent.mkdir(parents=True, exist_ok=True)
    marker = "<!-- Add pending items with date added -->"
    if marker in todos_content:
        idx = todos_content.index(marker) + len(marker)
        insert = "\n" + "\n".join(new_todos)
        new_content = todos_content[:idx] + insert + todos_content[idx:]
    else:
        new_content = todos_content + "\n" + "\n".join(new_todos) + "\n"

    _write(todos_path, new_content)
    print(_green(f"Synced {len(new_todos)} escalation(s) into knowledge/todos/pending.md"))
    for t in new_todos:
        print(f"  {t}")
    return 0


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def cmd_workspace(args: list[str]) -> int:
    """Router for workspace subcommands."""
    if not args or args[0] in ("-h", "--help", "help"):
        print(__doc__)
        return 0

    sub = args[0]
    rest = args[1:]

    match sub:
        case "init":
            return cmd_init(rest)
        case "context":
            return cmd_context(rest)
        case "sync":
            return cmd_sync(rest)
        case _:
            print(f"Unknown workspace subcommand: {sub}", file=sys.stderr)
            print("Run 'agent-toolkit workspace --help' for usage.", file=sys.stderr)
            return 1
