"""
OpenCode target adapter.

OpenCode supports two integration surfaces:

1. **Static companion assets** (generated by this adapter):
   `.opencode/skills/<name>/SKILL.md`    — on-demand procedures
   `.opencode/agents/<name>/AGENT.md`    — agent personas
   `.opencode/commands/<name>.md`        — slash commands (future)
   `opencode.json`                       — minimal, portable model config

   These companion assets work without any runtime code and are
   discoverable by OpenCode from the project root.

2. **Runtime TypeScript plugin** (NOT implemented here — see issue #10):
   A proper npm/Bun package in `packages/opencode-plugin/` that exports
   a plugin function and receives the full OpenCode context API.
   This is required for lifecycle hooks, custom tools, MCP configuration,
   and model/tool-call interception.

   The static adapter explicitly reports what requires the runtime plugin.

Official docs: https://opencode.ai/docs/plugins/
Research: docs/research/platform-capability-matrix.md (2026-08-04)

Key differences from Claude Code/Cursor:
- No JSON manifest (JS/TS modules, not plugin.json)
- Distribution: npm or local path (not git marketplace)
- Skills go in .opencode/skills/, agents in .opencode/agents/
- opencode.json for model config MUST NOT contain private provider URLs
"""
from __future__ import annotations

import json
from pathlib import Path

from agent_toolkit.compiler.model import (
    Agent,
    CanonicalGraph,
    CompilationResult,
    Product,
    Skill,
)
from agent_toolkit.compiler.targets.base import TargetAdapter


# opencode.json safe defaults — NO private providers, NO hardcoded models.
# Users customize their own ~/.config/opencode/opencode.json.
_OPENCODE_JSON_TEMPLATE = {
    "$schema": "https://opencode.ai/config.schema.json",
}

# opencode.json fields that indicate private/personal configuration.
# These must never appear in generated output.
_FORBIDDEN_OPENCODE_FIELDS = {
    "provider",     # provider config with baseURL can contain private LAN URLs
}


class OpenCodeAdapter(TargetAdapter):
    """Compiles agent-toolkit products into OpenCode companion assets.

    Generates static companion assets discoverable by OpenCode from the project root.
    Does NOT generate a runtime TypeScript plugin (that requires packages/opencode-plugin/).

    Capability parity:
      native (static):  skills (.opencode/skills/), agents (.opencode/agents/)
      generated:        opencode.json (minimal portable model config)
      unsupported:      lifecycle hooks, custom tools, MCP config, model interception
                        (all require the runtime TypeScript plugin — issue #10)
      unsupported:      plugin marketplace (OpenCode uses npm/git, not marketplace)
    """

    target_id = "opencode"
    package_type = "companion-assets"  # NOT a plugin — accurately named
    maturity = "stable"

    def compile(self, graph: CanonicalGraph, product: Product) -> CompilationResult:
        result = CompilationResult(target=self.target_id, product=product.id)
        out_dir = self.output_root / product.id

        # 1. Generate minimal opencode.json (safe defaults only)
        self._write_file(
            out_dir / "opencode.json",
            json.dumps(_OPENCODE_JSON_TEMPLATE, indent=2) + "\n",
            result,
        )
        result.emitted.append("opencode-config")

        # 2. Emit skills to .opencode/skills/
        for skill_id in product.included_skills:
            skill = graph.skills.get(skill_id)
            if skill is None:
                result.warnings.append(f"Skill '{skill_id}' not found — skipping")
                result.omitted.append(f"skill:{skill_id}")
                continue
            self._emit_skill(skill, out_dir, result)

        # 3. Emit agents to .opencode/agents/
        for agent_id in product.included_agents:
            agent = graph.agents.get(agent_id)
            if agent is None:
                result.warnings.append(f"Agent '{agent_id}' not found — skipping")
                result.omitted.append(f"agent:{agent_id}")
                continue
            self._emit_agent(agent, out_dir, result)

        # 4. Explicitly document what requires the runtime TypeScript plugin
        result.unsupported.extend([
            "lifecycle hooks — requires packages/opencode-plugin/ TypeScript runtime (issue #10)",
            "custom tools — requires TypeScript plugin with tool registration API",
            "MCP server config — requires TypeScript plugin (no static opencode.json format)",
            "model/tool-call interception — requires TypeScript plugin",
            "plugin marketplace install — OpenCode uses npm/Bun; no marketplace format",
        ])

        return result

    # ── opencode.json ─────────────────────────────────────────────────────────

    @staticmethod
    def validate_opencode_json(data: dict) -> list[str]:
        """Return error messages for any forbidden opencode.json fields."""
        errors = []
        for field in _FORBIDDEN_OPENCODE_FIELDS:
            if field in data:
                errors.append(
                    f"Forbidden field '{field}' in opencode.json — "
                    "provider config can contain private LAN URLs and must not ship publicly"
                )
        # Check for private hostnames in the whole JSON blob
        text = json.dumps(data)
        for pattern in (".local", "192.168.", "10.", "172.16."):
            if pattern in text:
                errors.append(
                    f"Possible private hostname '{pattern}' in opencode.json — "
                    "public distributions must never contain machine-specific URLs"
                )
        return errors

    # ── skills ────────────────────────────────────────────────────────────────

    def _emit_skill(self, skill: Skill, out_dir: Path, result: CompilationResult) -> None:
        """Copy SKILL.md to .opencode/skills/<name>/SKILL.md.

        OpenCode discovers skills at .opencode/skills/<name>/SKILL.md.
        Same Agent Skills format as Claude Code and Cursor.
        """
        if not skill.source_path.exists():
            result.warnings.append(f"Skill source missing: {skill.source_path}")
            result.omitted.append(f"skill:{skill.id}")
            return

        dst = out_dir / ".opencode" / "skills" / skill.name
        dst.mkdir(parents=True, exist_ok=True)

        content = skill.source_path.read_text(encoding="utf-8", errors="replace")
        self._write_file(dst / "SKILL.md", content, result)

        # Progressive disclosure: copy references/
        self._copy_skill_references(skill, dst, result)

        result.emitted.append(f"skill:{skill.id}")

    # ── agents ────────────────────────────────────────────────────────────────

    def _emit_agent(self, agent: Agent, out_dir: Path, result: CompilationResult) -> None:
        """Copy AGENT.md to .opencode/agents/<name>/AGENT.md."""
        if not agent.source_path.exists():
            result.warnings.append(f"Agent source missing: {agent.source_path}")
            result.omitted.append(f"agent:{agent.id}")
            return

        dst = out_dir / ".opencode" / "agents" / agent.name
        dst.mkdir(parents=True, exist_ok=True)

        content = agent.source_path.read_text(encoding="utf-8", errors="replace")
        self._write_file(dst / "AGENT.md", content, result)
        result.emitted.append(f"agent:{agent.id}")

    # ── parity notes ──────────────────────────────────────────────────────────

    @staticmethod
    def typescript_plugin_status() -> str:
        """Document TypeScript runtime plugin gap for certification."""
        return (
            "pending TypeScript runtime plugin — packages/opencode-plugin/ must export "
            "OpenCode's plugin function for hooks, MCP, custom tools, and tool-call "
            "interception (issue #10)"
        )

    @staticmethod
    def parity_notes() -> str:
        return (
            "OpenCode companion assets are static files discoverable from the project "
            "root. They work without any runtime code.\n"
            "\n"
            "The full OpenCode plugin API (lifecycle hooks, custom tools, MCP config, "
            "model interception) requires a TypeScript package in packages/opencode-plugin/ "
            "that exports a plugin function receiving the OpenCode context API. "
            "This is a separate work item (see issue #10).\n"
            "\n"
            "opencode.json is generated with safe defaults only (no provider config, "
            "no hardcoded model). Users customize their own ~/.config/opencode/opencode.json "
            "for model selection. This prevents the DEFECT-002 class of bugs where "
            "private LAN URLs get committed to public repositories."
        )
