"""
Windsurf / Devin Desktop target adapter.

Windsurf (and Devin Desktop, which uses the same distribution surface) does NOT
have a plugin marketplace. From research (2026-08-04):

  "You cannot install extensions through any marketplace on Devin Desktop."

This adapter generates a **customization bundle** — a set of static files that
are placed into a project repository and discovered by Windsurf / Devin Desktop
at startup. There is no formal Windsurf extension format.

Generated artifacts:
  AGENTS.md                   — directory-scoped instructions (picked up automatically)
  rules/<name>.mdc            — behavioral constraints (always-on, NOT memories)
  skills/<name>/SKILL.md      — on-demand procedures

NOT generated:
  Memories — NOT generated. Memories are personal/per-user state and must not
             be distributed as a project-level source of truth. Windsurf memories
             live in the user's profile, not in a shared repository artifact.
  Plugin manifest — no marketplace means no manifest format to target.

Semantic distinctions preserved (from ADR-002):
  Rules  = behavioral constraints (always-on in session context)
  Skills = on-demand procedures with supporting resources
  Memories = personal state — deliberately NOT generated by this adapter

Unsupported:
  Lifecycle hooks — no official Windsurf extension format for hooks
  MCP configuration — no official Windsurf MCP configuration format

Default scope: project (never global by auto-detection). Windsurf picks up
AGENTS.md and rules/ from the project root when the workspace is opened.

Research: docs/research/platform-capability-matrix.md (2026-08-04)
"""

from __future__ import annotations

from pathlib import Path

from agent_toolkit.compiler.model import (
    Agent,
    CanonicalGraph,
    CompilationResult,
    Product,
    Skill,
)
from agent_toolkit.compiler.targets.base import TargetAdapter

# .mdc frontmatter template for Windsurf behavioral rules.
# alwaysApply: true means the rule is injected into every session context.
_MDC_RULE_HEADER = """\
---
description: {description}
alwaysApply: true
---
"""


class WindsurfAdapter(TargetAdapter):
    """Compiles agent-toolkit products into Windsurf / Devin Desktop customization bundles.

    Windsurf has no plugin marketplace. The output is a set of static files
    committed to a project repository. Windsurf discovers AGENTS.md, rules/,
    and skills/ from the project root automatically.

    Capability parity:
      native:          AGENTS.md, rules/*.mdc (behavioral constraints), skills
      not-generated:   memories (personal state — must not be distributed; see ADR-002)
      unsupported:     hooks (no official Windsurf extension format)
      unsupported:     MCP (no official Windsurf MCP configuration format)
      not-applicable:  plugin manifest (Windsurf has no marketplace)

    Scope:
      Always project-scoped. Global installation of shared skills bundles is
      not supported via this surface (no ~/.windsurf/ equivalent for team packs).
    """

    target_id = "windsurf"
    package_type = "customization-bundle"  # explicitly NOT "plugin" — no marketplace
    maturity = "stable"

    def compile(self, graph: CanonicalGraph, product: Product) -> CompilationResult:
        result = CompilationResult(target=self.target_id, product=product.id)
        out_dir = self.output_root / product.id

        # 1. Emit AGENTS.md — directory-scoped instructions
        self._emit_agents_md(product, graph, out_dir, result)

        # 2. Emit skills to skills/<name>/SKILL.md
        for skill_id in product.included_skills:
            skill = graph.skills.get(skill_id)
            if skill is None:
                result.warnings.append(f"Skill '{skill_id}' not found — skipping")
                result.omitted.append(f"skill:{skill_id}")
                continue
            self._emit_skill(skill, out_dir, result)

        # 3. Emit rules to rules/<name>.mdc from agent behavioral constraints
        for agent_id in product.included_agents:
            agent = graph.agents.get(agent_id)
            if agent is None:
                result.warnings.append(f"Agent '{agent_id}' not found — skipping")
                result.omitted.append(f"agent:{agent_id}")
                continue
            self._emit_rule(agent, out_dir, result)

        # 4. Explicitly document unsupported / intentionally-not-generated surfaces.
        #    Never silently drop a capability — always report.
        result.unsupported.extend(
            [
                "hooks — no official Windsurf extension format for lifecycle hooks",
                "mcp — no official Windsurf MCP configuration format",
                "memories — intentionally NOT generated; memories are personal per-user "
                "state and must not be distributed as a shared project artifact (ADR-002). "
                "Users manage their own Windsurf memories independently.",
                "plugin-manifest — Windsurf has no marketplace; no manifest format to target",
            ]
        )

        return result

    # ── AGENTS.md ─────────────────────────────────────────────────────────────

    def _emit_agents_md(
        self,
        product: Product,
        graph: CanonicalGraph,
        out_dir: Path,
        result: CompilationResult,
    ) -> None:
        """Generate AGENTS.md — the directory-scoped instructions file.

        Windsurf reads AGENTS.md from the project root when a workspace is opened.
        It provides the AI with context about the project, available skills, and
        agent personas without requiring explicit user invocation.
        """
        lines = [
            f"# {product.name}",
            "",
            product.description,
            "",
        ]

        if product.included_skills:
            lines.extend(["## Available Skills", ""])
            for skill_id in product.included_skills:
                skill = graph.skills.get(skill_id)
                if skill:
                    desc = skill.description[:80]
                    lines.append(f"- **{skill.name}**: {desc}")
            lines.append("")

        if product.included_agents:
            lines.extend(["## Available Agents", ""])
            for agent_id in product.included_agents:
                agent = graph.agents.get(agent_id)
                if agent:
                    desc = agent.description[:80]
                    lines.append(f"- **{agent.name}**: {desc}")
            lines.append("")

        lines.extend(
            [
                "## Scope",
                "",
                "These instructions are project-scoped. Rules in `rules/` provide "
                "always-on behavioral constraints. Skills in `skills/` are on-demand "
                "procedures invoked explicitly.",
                "",
            ]
        )

        content = "\n".join(lines)
        self._write_file(out_dir / "AGENTS.md", content, result)
        result.emitted.append("AGENTS.md")

    # ── skills ────────────────────────────────────────────────────────────────

    def _emit_skill(self, skill: Skill, out_dir: Path, result: CompilationResult) -> None:
        """Copy SKILL.md to skills/<name>/SKILL.md.

        Windsurf discovers skills at skills/<name>/SKILL.md — the same path
        convention as Claude Code, Cursor, and OpenCode. Skills are on-demand
        procedures, NOT behavioral constraints. Users invoke them explicitly.

        Semantic distinction (ADR-002): Skills != Rules. Do not merge them.
        """
        if not skill.source_path.exists():
            result.warnings.append(f"Skill source missing: {skill.source_path}")
            result.omitted.append(f"skill:{skill.id}")
            return

        dst = out_dir / "skills" / skill.name
        dst.mkdir(parents=True, exist_ok=True)

        content = skill.source_path.read_text(encoding="utf-8", errors="replace")
        self._write_file(dst / "SKILL.md", content, result)

        # Progressive disclosure: copy references/
        self._copy_skill_references(skill, dst, result)

        result.emitted.append(f"skill:{skill.id}")

    # ── rules ─────────────────────────────────────────────────────────────────

    def _emit_rule(self, agent: Agent, out_dir: Path, result: CompilationResult) -> None:
        """Emit a Windsurf .mdc rule from an agent persona's behavioral constraints.

        Rules are ALWAYS-ON behavioral constraints injected into every session.
        They are semantically distinct from Skills (on-demand) and Memories
        (personal user state). See ADR-002 for the full semantic contract.

        The rule content is derived from the agent's instruction body — trimmed to
        the behavioral constraints portion. The full agent persona is available in
        AGENTS.md; the rule provides the always-applicable subset.

        NOT generated: memories. Memories are personal per-user state and MUST NOT
        be distributed as source-of-truth artifacts.
        """
        if not agent.source_path.exists():
            result.warnings.append(f"Agent source missing: {agent.source_path}")
            result.omitted.append(f"agent:{agent.id}")
            return

        content = agent.source_path.read_text(encoding="utf-8", errors="replace")

        # Build .mdc with frontmatter + agent instruction body.
        # alwaysApply: true — Windsurf injects this into every session context.
        header = _MDC_RULE_HEADER.format(
            description=agent.description[:100].replace("\n", " "),
        )
        rule_content = header + "\n" + content

        rules_dir = out_dir / "rules"
        rules_dir.mkdir(parents=True, exist_ok=True)
        self._write_file(rules_dir / f"{agent.name}.mdc", rule_content, result)
        result.emitted.append(f"rule:{agent.id}")

    # ── parity notes ──────────────────────────────────────────────────────────

    @staticmethod
    def parity_notes() -> str:
        return (
            "Windsurf / Devin Desktop has no plugin marketplace. This adapter generates "
            "a customization bundle (project-scoped static files) that Windsurf picks "
            "up automatically when a workspace is opened.\n"
            "\n"
            "Semantic distinctions preserved (ADR-002):\n"
            "  Rules   = behavioral constraints (always-on, rules/*.mdc)\n"
            "  Skills  = on-demand procedures (explicit invocation, skills/*/SKILL.md)\n"
            "  Memories = personal per-user state — deliberately NOT generated here\n"
            "\n"
            "Memories are intentionally excluded because they represent personal user "
            "state. Distributing memories as a shared project artifact would override "
            "individual user configurations and violate the separation between shared "
            "project knowledge and personal assistant memory.\n"
            "\n"
            "Hooks and MCP are not supported — there is no official Windsurf extension "
            "format for either surface. Future versions may add support once Windsurf "
            "publishes an extension API.\n"
            "\n"
            "Scope is always project-level. Global team-wide installation of skill "
            "bundles is not supported through this surface."
        )
