#!/usr/bin/env bash
# install-desktop.sh — install/uninstall Agent Toolkit Desktop from the
# release archive into XDG user locations (#1057/#1116, #1130 vertical).
#
# install:   ./install-desktop.sh install
# uninstall: ./install-desktop.sh uninstall
#
# XDG-compliant, no sudo:
#   binary  → ${XDG_DATA_HOME:-~/.local/share}/agent-toolkit/bin
#   desktop → ${XDG_DATA_HOME:-~/.local/share}/applications
#   icons   → ${XDG_DATA_HOME:-~/.local/share}/icons/hicolor/<size>/apps
#   man     → ${XDG_DATA_HOME:-~/.local/share}/man/man1
#   receipt → ${XDG_CONFIG_HOME:-~/.config}/agent-toolkit/receipts
#
# Ownership follows the product's install-receipt semantics (schemaVersion 1):
# 'created' files are removed on uninstall; destinations that pre-existed the
# install and are NOT owned by a previous receipt of this product are USER
# data — recorded 'merged', never overwritten at install, never removed at
# uninstall. Upgrade paths (our own previous receipt owns the file) overwrite
# as 'created'. JSON receipts are generated by python3 — never hand-assembled.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
PRODUCT="agent-toolkit-desktop"
TARGET="linux"
SCHEMA_VERSION=1

XDG_DATA="${XDG_DATA_HOME:-$HOME/.local/share}"
XDG_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}"
BIN_DIR="$XDG_DATA/agent-toolkit/bin"
RECEIPT_DIR="$XDG_CONFIG/agent-toolkit/receipts"
RECEIPT="$RECEIPT_DIR/${PRODUCT}-${TARGET}.json"
DESKTOP_SRC="$HERE/${PRODUCT}.desktop"

need_file() { [ -f "$1" ] || { echo "error: missing $1 (run from the extracted archive)" >&2; exit 2; }; }

sha256_of() { sha256sum "$1" | cut -d' ' -f1; }

install_desktop() {
  need_file "$HERE/$PRODUCT"
  need_file "$DESKTOP_SRC"
  need_file "$HERE/install-desktop.sh"
  need_file "$HERE/VERSION"
  [ -d "$HERE/icons" ] || { echo "error: missing icons/ directory" >&2; exit 2; }
  [ -f "$HERE/share/man/man1/${PRODUCT}.1" ] || { echo "error: missing man page" >&2; exit 2; }

  mkdir -p "$BIN_DIR" "$XDG_DATA/applications" "$RECEIPT_DIR" \
    "$XDG_DATA/icons/hicolor/scalable/apps" "$XDG_DATA/man/man1"

  local version
  version="$(tr -d ' \n' < "$HERE/VERSION")"
  local digest="none"
  command -v sha256sum >/dev/null 2>&1 && digest="$(sha256_of "$HERE/$PRODUCT")"
  local installed_at
  installed_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

  # Planning + application + receipt in one python3 pass (paths with quotes
  # or pipes are JSON-safe; ownership semantics implemented exactly once).
  BIN_DIR="$BIN_DIR" XDG_DATA="$XDG_DATA" RECEIPT_DIR="$RECEIPT_DIR" \
  RECEIPT="$RECEIPT" PRODUCT="$PRODUCT" TARGET="$TARGET" SCHEMA_VERSION="$SCHEMA_VERSION" \
  VERSION_STR="$version" DIGEST="$digest" INSTALLED_AT="$installed_at" \
  HERE="$HERE" \
  python3 <<'PY'
import hashlib, json, os, shutil

product = os.environ["PRODUCT"]
receipt_dir = os.environ["RECEIPT_DIR"]
here = os.environ["HERE"]
xdg_data = os.environ["XDG_DATA"]
bin_dir = os.environ["BIN_DIR"]

def dst_digest(path):
    return hashlib.sha256(open(path, "rb").read()).hexdigest() if os.path.isfile(path) else ""

def dst_matches_ours(dst):
    """true when the destination content equals what our receipt recorded."""
    for fn in os.listdir(receipt_dir):
        if not fn.endswith(".json"):
            continue
        try:
            r = json.load(open(os.path.join(receipt_dir, fn)))
        except Exception:
            continue
        if r.get("product") != product:
            continue
        for a in r.get("artifacts", []):
            if a.get("path") == dst and a.get("ownership") == "created":
                recorded = a.get("digest", "")
                return recorded != "" and dst_digest(dst) == recorded
    return False

plan = []
def add(src, dst, mode=0o644):
    own = "created"
    if os.path.exists(dst):
        if dst_matches_ours(dst):
            own = "created"  # ours, unchanged → upgrade
        else:
            own = "merged"   # user-modified or user file → preserve
    plan.append({"src": src, "dst": dst, "mode": mode, "ownership": own})

add(os.path.join(here, product), os.path.join(bin_dir, product), 0o755)
add(os.path.join(here, "install-desktop.sh"),
    os.path.join(bin_dir, f"{product}-installer.sh"), 0o755)
add(os.path.join(here, f"{product}.desktop"),
    os.path.join(xdg_data, "applications", f"{product}.desktop"))
for size in (16, 24, 32, 48, 64, 128, 256, 512):
    add(os.path.join(here, "icons", f"{product}-{size}.png"),
        os.path.join(xdg_data, "icons", "hicolor", f"{size}x{size}", "apps", f"{product}.png"))
# Installed name must equal the Icon= basename (hicolor lookup finds
# scalable/apps/<name>.svg, never <name>-scalable.svg).
add(os.path.join(here, "icons", f"{product}-scalable.svg"),
    os.path.join(xdg_data, "icons", "hicolor", "scalable", "apps", f"{product}.svg"))
add(os.path.join(here, "share", "man", "man1", f"{product}.1"),
    os.path.join(xdg_data, "man", "man1", f"{product}.1"))

merged = created = 0
receipt_path = os.environ["RECEIPT"]
os.makedirs(os.path.dirname(receipt_path), exist_ok=True)
artifacts = []
for step in plan:
    dst, src, mode, own = step["dst"], step["src"], step["mode"], step["ownership"]
    if own == "merged":
        # user data: leave the file untouched, record it as preserved
        merged += 1
    else:
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copyfile(src, dst)
        os.chmod(dst, mode)
        created += 1
        # .desktop Exec → installed binary (launcher sessions lack
        # ~/.local/bin PATH) — the digest below must capture the REWRITTEN
        # file, or the next install misclassifies it as user-modified
        if dst.endswith(".desktop"):
            lines = []
            for line in open(dst):
                lines.append(f"Exec={bin_dir}/{product}\n" if line.startswith("Exec=") else line)
            open(dst, "w").writelines(lines)
    artifacts.append({"path": dst,
                      "digest": dst_digest(dst),
                      "ownership": own})

receipt = {
    "schemaVersion": int(os.environ["SCHEMA_VERSION"]),
    "product": product,
    "target": os.environ["TARGET"],
    "scope": "user",
    "version": os.environ["VERSION_STR"],
    "installedAt": os.environ["INSTALLED_AT"],
    "sourceDigest": os.environ["DIGEST"],
    "artifacts": artifacts,
    "configPatches": [],
    "secrets": [],
}
tmp = receipt_path + ".tmp"
with open(tmp, "w") as f:
    json.dump(receipt, f, indent=2)
    f.write("\n")
os.replace(tmp, receipt_path)
print(f"receipt: {receipt_path}")
print(f"installed: created={created} merged(preserved)={merged}")
PY
  command -v update-desktop-database >/dev/null 2>&1 && update-desktop-database "$XDG_DATA/applications" || true
  command -v gtk-update-icon-cache >/dev/null 2>&1 && gtk-update-icon-cache -q "$XDG_DATA/icons/hicolor" || true
  echo "installed: $BIN_DIR/$PRODUCT"
  echo "launcher:  $XDG_DATA/applications/${PRODUCT}.desktop (menu entry; icon installed for all hicolor sizes)"
}

uninstall_desktop() {
  [ -f "$RECEIPT" ] || { echo "no install receipt at $RECEIPT — nothing to uninstall" >&2; exit 3; }
  # remove only 'created' artifacts; 'merged' (pre-existing) files are kept
  python3 - "$RECEIPT" <<'PY'
import json, os, sys
r = json.load(open(sys.argv[1]))
removed = kept = 0
for a in r.get("artifacts", []):
    p = a.get("path", "")
    if a.get("ownership") == "created" and os.path.isfile(p):
        os.remove(p)
        removed += 1
        d = os.path.dirname(p)
        try:
            if not os.listdir(d):
                os.rmdir(d)
        except OSError:
            pass
    else:
        kept += 1
print(f"removed {removed} owned file(s); preserved {kept} pre-existing")
PY
  rm -f "$RECEIPT"
  command -v update-desktop-database >/dev/null 2>&1 && update-desktop-database "$XDG_DATA/applications" || true
  echo "uninstalled: launcher entry, icons, man page and binary (receipt-backed)"
}

case "${1:-install}" in
  install) install_desktop ;;
  uninstall) uninstall_desktop ;;
  *) echo "usage: $0 [install|uninstall]" >&2; exit 1 ;;
esac
