#!/usr/bin/env python3
import os, pathlib
ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "modules/agent_toolkit_core/embedded_data.v"
DIRS = ["skills", "loops", "profiles", "mcp", "catalogs", "agents", "capabilities", "distributions", "plugins", "packs"]
files=[]
for d in DIRS:
    p = ROOT / d
    if not p.exists(): continue
    for fp in p.rglob("*"):
        if fp.is_file():
            rel = fp.relative_to(ROOT).as_posix()
            v_rel = os.path.join("../..", rel)
            files.append((rel, v_rel, fp))
files.sort(key=lambda x: x[0])
with open(OUT, "w") as f:
    f.write("module agent_toolkit_core\n\n")
    f.write("import v.embed_file\n\n")
    f.write("// Code generated by scripts/generate-embedded-data.py — DO NOT EDIT.\n")
    f.write("// Regenerate: python3 scripts/generate-embedded-data.py\n")
    f.write(f"// Payload: {len(files)} files, embedded via $embed_file at compile time.\n\n")
    for i, (rel, v_rel, _) in enumerate(files):
        f.write(f"const ef_{i} = $embed_file('{v_rel}')\n")
    f.write("\n")
    f.write("const embedded_file_map = {\n")
    for i, (rel, _, _) in enumerate(files):
        f.write(f"\t'{rel}': ef_{i}.to_string()\n")
    f.write("}\n\n")
    dirs=set()
    for rel, _, _ in files:
        parts=rel.split("/")
        for j in range(1, len(parts)):
            dirs.add("/".join(parts[:j]))
    for d in DIRS:
        if (ROOT/d).exists():
            dirs.add(d)
    f.write("const embedded_dir_set = {\n")
    for d in sorted(dirs):
        f.write(f"\t'{d}': true\n")
    f.write("}\n\n")
    f.write(r"""
pub fn embedded_has_file(path string) bool {
    return path in embedded_file_map
}
pub fn embedded_is_file(path string) bool {
    return path in embedded_file_map
}
pub fn embedded_is_dir(path string) bool {
    if path in embedded_dir_set {
        return true
    }
    prefix := path + '/'
    for k, _ in embedded_file_map {
        if k.starts_with(prefix) {
            return true
        }
    }
    return false
}
pub fn embedded_read_file(path string) !string {
    if path in embedded_file_map {
        return embedded_file_map[path]
    }
    return error('embedded file not found: ${path}')
}
pub fn embedded_ls(dir string) []string {
    mut out := []string{}
    mut seen := map[string]bool{}
    prefix := if dir.len == 0 { '' } else { dir + '/' }
    for k, _ in embedded_file_map {
        if !k.starts_with(prefix) {
            continue
        }
        rest := k[prefix.len..]
        idx := rest.index('/') or { -1 }
        name := if idx == -1 { rest } else { rest[..idx] }
        if name.len == 0 {
            continue
        }
        if name !in seen {
            seen[name] = true
            out << name
        }
    }
    out.sort()
    return out
}
pub fn embedded_is_valid_root() bool {
    has_profiles := 'profiles' in embedded_dir_set
    has_skills := 'skills' in embedded_dir_set
    has_loops := 'loops' in embedded_dir_set
    if !has_profiles {
        return false
    }
    return has_skills || has_loops
}
pub fn embedded_is_repo_checkout() bool {
    return 'skills' in embedded_dir_set && 'loops' in embedded_dir_set
}
""")
print(f"Wrote {OUT} with {len(files)} files")
