#!/usr/bin/env -S v run

import os

const dirs = ['skills', 'loops', 'profiles', 'mcp', 'catalogs', 'agents', 'capabilities', 'distributions', 'plugins', 'packs']

fn main() {
	root := os.dir(@FILE) + '/..'
	out := os.join_path(root, 'modules', 'agent_toolkit_core', 'embedded_data.v')
	mut files := []string{}
	for d in dirs {
		p := os.join_path(root, d)
		if !os.is_dir(p) {
			continue
		}
		walk(p, root, mut files)
	}
	files.sort()
	mut out_content := ''
	out_content += 'module agent_toolkit_core\n\n'
	out_content += '// Code generated by scripts/generate-embedded-data.vsh — DO NOT EDIT.\n'
	out_content += '// Regenerate: v run scripts/generate-embedded-data.vsh\n'
	out_content += '// Payload: ${files.len} files, embedded via \$embed_file at compile time.\n\n'
	for i, rel in files {
		v_rel := '../../' + rel
		out_content += "const ef_${i} = \$embed_file('${v_rel}')\n"
	}
	out_content += '\n'
	out_content += 'const embedded_file_map = {\n'
	for i, rel in files {
		out_content += "\t'${rel}': ef_${i}.to_string()\n"
	}
	out_content += '}\n\n'
	mut dir_set := map[string]bool{}
	for rel in files {
		parts := rel.split('/')
		for j in 1 .. parts.len {
			dir_set[parts[..j].join('/')] = true
		}
	}
	for d in dirs {
		if os.is_dir(os.join_path(root, d)) {
			dir_set[d] = true
		}
	}
	mut dir_list := dir_set.keys()
	dir_list.sort()
	out_content += 'const embedded_dir_set = {\n'
	for d in dir_list {
		out_content += "\t'${d}': true\n"
	}
	out_content += '}\n\n'
	out_content += "
pub fn embedded_has_file(path string) bool {
\treturn path in embedded_file_map
}
pub fn embedded_is_file(path string) bool {
\treturn path in embedded_file_map
}
pub fn embedded_is_dir(path string) bool {
\tif path in embedded_dir_set {
\t\treturn true
\t}
\tprefix := path + '/'
\tfor k, _ in embedded_file_map {
\t\tif k.starts_with(prefix) {
\t\t\treturn true
\t\t}
\t}
\treturn false
}
pub fn embedded_read_file(path string) !string {
\tif path in embedded_file_map {
\t\treturn embedded_file_map[path]
\t}
\treturn error('embedded file not found: \${path}')
}
pub fn embedded_ls(dir string) []string {
\tmut out := []string{}
\tmut seen := map[string]bool{}
\tprefix := if dir.len == 0 { '' } else { dir + '/' }
\tfor k, _ in embedded_file_map {
\t\tif !k.starts_with(prefix) {
\t\t\tcontinue
\t\t}
\t\trest := k[prefix.len..]
\t\tidx := rest.index('/') or { -1 }
\t\tname := if idx == -1 { rest } else { rest[..idx] }
\t\tif name.len == 0 {
\t\t\tcontinue
\t\t}
\t\tif name !in seen {
\t\t\tseen[name] = true
\t\t\tout << name
\t\t}
\t}
\tout.sort()
\treturn out
}
pub fn embedded_is_valid_root() bool {
\thas_profiles := 'profiles' in embedded_dir_set
\thas_skills := 'skills' in embedded_dir_set
\thas_loops := 'loops' in embedded_dir_set
\tif !has_profiles {
\t\treturn false
\t}
\treturn has_skills || has_loops
}
pub fn embedded_is_repo_checkout() bool {
\treturn 'skills' in embedded_dir_set && 'loops' in embedded_dir_set
}
"
	os.write_file(out, out_content) or { panic(err) }
	println('Wrote ${out} with ${files.len} files')
}

fn walk(cur string, root string, mut out []string) {
	entries := os.ls(cur) or { return }
	for e in entries {
		p := os.join_path(cur, e)
		if os.is_dir(p) {
			walk(p, root, mut out)
		} else if os.is_file(p) {
			mut rel := p[root.len..].trim_string_left(os.path_separator)
			rel = rel.replace('\\', '/')
			out << rel
		}
	}
}
