// Code generated by scripts/generate_surface.py — DO NOT EDIT.
// Regenerate: python3 scripts/generate_surface.py
module agent_toolkit_server

pub struct TuiAction {
pub:
	name    string
	title   string
	method  string
	route   string
	scope   string
	confirm bool
}

pub fn tui_actions() []TuiAction {
	return [
		TuiAction{ name: 'help', title: 'Print consumer-first help text', method: 'GET', route: '/api/v1/help', scope: 'read:*', confirm: false },
		TuiAction{ name: 'version', title: 'Print agent-toolkit version string', method: 'GET', route: '/api/v1/version', scope: 'read:*', confirm: false },
		TuiAction{ name: 'install', title: 'Install profiles for detected or selected AI tools', method: 'POST', route: '/api/v1/install', scope: 'write:fs', confirm: true },
		TuiAction{ name: 'update', title: 'Refresh installed profiles from latest toolkit data', method: 'POST', route: '/api/v1/update', scope: 'write:fs', confirm: false },
		TuiAction{ name: 'uninstall', title: 'Remove toolkit-owned files using install receipts', method: 'POST', route: '/api/v1/uninstall', scope: 'write:fs', confirm: true },
		TuiAction{ name: 'doctor', title: 'Check toolkit data and tool availability', method: 'GET', route: '/api/v1/doctor', scope: 'read:*', confirm: false },
		TuiAction{ name: 'diff', title: 'Show changes vs installed plugin bundles', method: 'GET', route: '/api/v1/diff', scope: 'read:*', confirm: false },
		TuiAction{ name: 'skills', title: 'Sync, list, and validate skills', method: 'POST', route: '/api/v1/skills/{sub}', scope: 'write:catalog', confirm: true },
		TuiAction{ name: 'mcp', title: 'MCP provider setup, health, doctor, uninstall', method: 'POST', route: '/api/v1/mcp/{sub}', scope: 'write:mcp', confirm: true },
		TuiAction{ name: 'plugin', title: 'Plugin bundle sync and check', method: 'POST', route: '/api/v1/plugin/{sub}', scope: 'write:plugins', confirm: true },
		TuiAction{ name: 'loop', title: 'Loop engineering (init, run, status, audit, cost, schedule, sync)', method: 'POST', route: '/api/v1/loops/{sub}', scope: 'write:loops', confirm: false },
		TuiAction{ name: 'workspace', title: 'Workspace scaffolding (init, context, sync)', method: 'POST', route: '/api/v1/workspace/{sub}', scope: 'write:workspace', confirm: true },
		TuiAction{ name: 'memory', title: 'Knowledge base (add, search, inject, review, todo)', method: 'POST', route: '/api/v1/memory/{sub}', scope: 'write:memory', confirm: false },
		TuiAction{ name: 'project', title: 'Project index (clone, list, add, remove, scan)', method: 'POST', route: '/api/v1/project/{sub}', scope: 'write:projects', confirm: true },
		TuiAction{ name: 'devcompanion', title: 'Background job queue', method: 'POST', route: '/api/v1/dc/{sub}', scope: 'write:dc', confirm: true },
		TuiAction{ name: 'insights', title: 'Local usage analytics (OpenCode, Cursor, Claude)', method: 'GET', route: '/api/v1/insights', scope: 'read:*', confirm: false },
		TuiAction{ name: 'build', title: 'Compile canonical capabilities into target artifacts', method: 'POST', route: '/api/v1/build', scope: 'write:plugins', confirm: true },
		TuiAction{ name: 'inventory', title: 'List skills, agents, and products', method: 'GET', route: '/api/v1/inventory', scope: 'read:*', confirm: false },
		TuiAction{ name: 'matrix', title: 'Platform capability matrix', method: 'GET', route: '/api/v1/matrix', scope: 'read:*', confirm: false },
		TuiAction{ name: 'release', title: 'Generate release artifacts (maintainer / CI)', method: 'POST', route: '/api/v1/release', scope: 'write:*', confirm: false },
		TuiAction{ name: 'swarm', title: 'Multi-agent swarm orchestration', method: 'POST', route: '/api/v1/swarms/{sub}', scope: 'write:swarm', confirm: true },
	]
}
