module agent_toolkit_core

// Remote execution scaffolding for loops (Phase 0, #729).
// v1.19.0 ships cadence→cron translator + backend registry (github-actions only).

// cadence_to_cron converts toolkit cadence (e.g. 15m, 4h, 1d, 1w) to GitHub Actions cron.
// Supported: <N>m (1-59), <N>h (1-23, 24→daily), <N>d, 1w. Invalid → error.
pub fn cadence_to_cron(cadence string) !string {
	c := cadence.trim_space()
	if c.len < 2 {
		return error('invalid cadence "${cadence}" — expected <N>m|h|d|w e.g. 15m, 4h, 1d, 1w')
	}
	unit := c[c.len - 1..]
	num_str := c[..c.len - 1]
	if num_str.len == 0 {
		return error('invalid cadence "${cadence}" — missing number')
	}
	for ch in num_str {
		if ch < `0` || ch > `9` {
			return error('invalid cadence "${cadence}" — expected <N>m|h|d|w')
		}
	}
	num := num_str.int()
	if num <= 0 {
		return error('invalid cadence "${cadence}" — N must be >0')
	}
	if unit == 'm' {
		if num > 59 {
			return error('invalid cadence "${cadence}" — minutes must be 1-59 (use hours for larger)')
		}
		if num == 1 {
			return '* * * * *'
		}
		return '*/${num} * * * *'
	} else if unit == 'h' {
		if num == 24 {
			return '0 0 * * *'
		}
		if num > 23 {
			return error('invalid cadence "${cadence}" — hours must be 1-24')
		}
		if num == 1 {
			return '0 * * * *'
		}
		return '0 */${num} * * *'
	} else if unit == 'd' {
		if num == 1 {
			return '0 0 * * *'
		}
		return '0 0 */${num} * *'
	} else if unit == 'w' {
		if num != 1 {
			return error('invalid cadence "${cadence}" — only 1w supported (weekly)')
		}
		return '0 0 * * 0'
	} else {
		return error('invalid cadence "${cadence}" — expected suffix m|h|d|w')
	}
}

// remote_platforms lists supported remote backends for loop schedule.
// v1.19.0: local (default, OS schedulers) + github-actions. Others are future and return unsupported error.
pub fn remote_platforms() []string {
	return ['local', 'github-actions']
}

pub fn is_remote_platform(platform string) bool {
	for p in remote_platforms() {
		if p == platform {
			return true
		}
	}
	return false
}

// emit_github_workflow renders a GitHub Actions workflow for a loop.
// Phase 0: pure string template, no file I/O. Phase 1 will add file write + version pin.
pub fn emit_github_workflow(loop_name string, tier string, cadence string, cron string, version string) string {
	ver := if version.len > 0 { version } else { '1.18.0' }
	return '# Code generated by agent-toolkit loop schedule ${loop_name} --platform github-actions — DO NOT EDIT.\n# Regenerate: agent-toolkit loop schedule ${loop_name} --platform github-actions\n# Source: loops/${loop_name}/loop.yaml (cadence: ${cadence} → ${cron})\nname: agent-toolkit — ${loop_name} (${tier})\n\non:\n  schedule:\n    - cron: \'${cron}\'\n  workflow_dispatch:\n\nconcurrency:\n  group: agent-toolkit-${loop_name}\n  cancel-in-progress: false\n\npermissions:\n  contents: write\n  pull-requests: write\n  issues: write\n\njobs:\n  run:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - name: Setup uv + agent-toolkit\n        run: |\n          pip install -q uv\n          uvx --from agent-toolkit-cli==${ver} agent-toolkit --help\n      - name: Run loop\n        env:\n          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}\n          GH_TOKEN: \${{ secrets.GITHUB_TOKEN }}\n        run: uvx --from agent-toolkit-cli==${ver} agent-toolkit loop run ${loop_name} --non-interactive\n'
}
