module agent_toolkit_core

const workspace_agents_md = '# AGENTS.md — AI Workspace Orchestrator

> Generated by: agent-toolkit workspace init
> Customize this file to reflect your team\'s workflows and tools.

**Purpose**: Session that orchestrates multi-repository work.

## Work Context

- **Repos**: ./projects/ symlinks · ./repos/ cloned on-demand
- **Knowledge**: ./knowledge/ — persistent memory across sessions
- **Personas**: ./personas/ — focused work modes
- **Packs**: ./packs/ — context bundles per client/project

## Available Commands

```
agent-toolkit workspace context        # Print session snapshot
agent-toolkit workspace sync           # Sync loop escalations into todos
agent-toolkit memory add --type <t>    # Add learning/process/todo
agent-toolkit memory search <query>    # Search knowledge base
agent-toolkit memory inject            # Output context block for session
agent-toolkit memory todo              # List pending todos
agent-toolkit project clone <org/repo> # Clone a repo and symlink it
agent-toolkit project list             # List indexed projects
agent-toolkit project scan             # Check project/repo consistency
```

## Operating Rules

- Run `agent-toolkit workspace context` at session start
- Run `agent-toolkit memory search <topic>` before asking known questions
- Save discoveries: `agent-toolkit memory add --type learning "..."`
- Queue background work: `agent-toolkit devcompanion queue <project>`
'

const workspace_knowledge_readme = '# Knowledge Base

Persistent memory across sessions. Add entries with:

```
agent-toolkit memory add --type learning "Always run tests before committing"
agent-toolkit memory add --type process "How to deploy: ..."
agent-toolkit memory add --type todo "Investigate slow query in reports"
```

## Structure

- `learnings/general.md` — factual session learnings
- `processes/<topic>.md` — how-to procedures
- `todos/pending.md` — pending follow-ups
'

const workspace_learnings_general = '# General Learnings

<!-- Add new entries with: agent-toolkit memory add --type learning "..." -->

| Date | Learning | Context |
|------|----------|---------|
'

const workspace_todos_pending = '# Pending Todos

<!-- Add pending items with date added -->
<!-- agent-toolkit memory add --type todo "description" -->
'

const workspace_packs_readme = '# Packs

Context bundles for switching between clients or projects.

Create a YAML file here:

```yaml
# packs/my-client.yaml
name: my-client
description: Context for my-client engagement
projects:
  - my-client-api
  - my-client-frontend
notes: |
  Key contacts: ...
```

Load with: `agent-toolkit workspace load packs/my-client.yaml`

Snapshot with: `agent-toolkit workspace context`
'

const workspace_gitignore = '# Cloned repos (managed by agent-toolkit project clone)
repos/
# Project symlinks (managed by agent-toolkit project clone/add)
projects/
# Active state files
.active-persona
.active-pack
.active-profile
.active-skills
.active-loops
.persona-history
'

const workspace_persona_implementer = '---
allow:
  - write_files
  - run_tests
  - run_build
  - create_commits
deny:
  - merge_prs
  - deploy_production
output_format: code_first
handoffs:
  - when: "implementation complete, needs review"
    to: reviewer
---

# Implementer Persona

> Bias toward action. Write code, run tests, create commits.

## Focus

- Write clean, idiomatic code following project conventions
- Run tests to verify changes work
- Create commits with clear messages
- Ask only when genuinely blocked

## Constraints

- **Do not** merge PRs or deploy to production
- Handoff to **reviewer** when implementation is complete
'

const workspace_persona_reviewer = '---
allow:
  - read_files
  - run_tests
  - post_comments
  - approve_prs
deny:
  - write_files
  - create_commits
output_format: critique_and_feedback
handoffs:
  - when: "review complete, changes needed"
    to: implementer
  - when: "security concerns found"
    to: architect
---

# Reviewer Persona

> Analyze and critique. No changes — feedback only.

## Focus

- Read code carefully for correctness, clarity, and security
- Run tests to verify coverage
- Post clear, actionable feedback
- Approve PRs when quality bar is met

## Constraints

- **Do not** write or modify files
- **Do not** create commits
- Handoff to **implementer** when changes are needed
'

const workspace_persona_researcher = '---
allow:
  - read_files
  - search_web
  - read_docs
deny:
  - write_files
  - create_commits
  - run_tests
output_format: summary_and_findings
handoffs:
  - when: "research complete, ready to implement"
    to: implementer
  - when: "architectural decision needed"
    to: architect
---

# Researcher Persona

> Explore and summarize. No implementation.

## Focus

- Read codebases to understand structure and patterns
- Search documentation and references
- Produce clear summaries of findings
- Identify options with tradeoffs

## Constraints

- **Do not** modify any files
- **Do not** run tests or builds
- Handoff to **implementer** or **architect** when done
'

const workspace_persona_architect = '---
allow:
  - read_files
  - write_docs
  - create_adrs
  - design_schemas
deny:
  - write_application_code
  - create_commits
output_format: design_document
handoffs:
  - when: "design finalized, ready to build"
    to: implementer
  - when: "security review needed"
    to: reviewer
---

# Architect Persona

> System design, tradeoffs, ADRs.

## Focus

- Analyze system design and architectural tradeoffs
- Write ADRs (Architecture Decision Records)
- Design schemas, APIs, and data models
- Evaluate technical options at the system level

## Constraints

- **Do not** write application code
- Write design documents and ADRs, not implementation
- Handoff to **implementer** when design is finalized
'
